version: '3'

services:
  a_level_nix_php:
    build: ./php
    container_name: a_level_nix_php
    volumes:
      - ../server:/var/www/html
    ports:
      - 8181:80
    environment:
      WEB_DOCUMENT_ROOT: /var/www/html/public
      WEB_DOCUMENT_INDEX: index.php
      PHP_MEMORY_LIMIT: 2G
      PHP_UPLOAD_MAX_FILESIZE: 512M
      PHP_POST_MAX_SIZE: 512M
      PHP_DISPLAY_ERRORS: 1
      php.xdebug.max_nesting_level: 500
    depends_on:
      - a_level_nix_mysql



  a_level_nix_mysql:
    build: ./mysql
    container_name: a_level_nix_mysql
    environment:
      MYSQL_ROOT_PASSWORD: cbece_gead-cebfa
      MYSQL_DATABASE: a_level_nix_mysql
    ports:
      - 3131:3306
    volumes:
      - a_level_nix-db:/var/lib/mysql
    

    
     
      
  phpmyadmin:
   image: phpmyadmin/phpmyadmin:latest
   restart: always
   ports:
     - '8088:80'
   environment:
     PMA_ARBITRARY: 0
     PMA_HOST: 'a_level_nix_mysql'
     MYSQL_ROOT_PASSWORD: 'cbece_gead-cebfa'
   depends_on:
     - a_level_nix_mysql


volumes:
  a_level_nix-db:
  

